### PR TITLE
Edwina.L.Rmd

### PR DESCRIPTION
**Pull request by Edwina-L**
[R_Exercises8.docx](https://github.com/CUNYSPHCode/IntroR/files/4852521/R_Exercises8.docx)

### CODE REVIEW

**Comment by LiNk-NY** [comment]
Make sure you are making changes to `R_Exercises8.Rmd` from your fork and creating a pull request. If you click `Files changed` at the top, you can see that there were no files changed.

**Comment by LiNk-NY** [comment]
@Edwina-L

**Comment by LiNk-NY** [comment]
If you've cloned it previously, you need to update your fork to the most up-to-date repository (this one `CUNYSPHCode/IntroR`). You do this by doing a `git pull` command from git or from a Git Graphical User Interface (GUI) such as `GitKraken` etc. You also have the option of deleting your fork and re-cloning. Make your changes to the `R_Exercises8.Rmd` file, commit, and create another PR.

**Comment by Edwina-L** [comment]
[R_Exercises8.docx](https://github.com/CUNYSPHCode/IntroR/files/4853887/R_Exercises8.docx)

**Pull request closed without merging**
